development:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: bgat66jdufxxh5pafvqybxkfxzt
    referrences:
      enrollments:
        db: bksfqeuhj
        fields:
          id: 3
          round_id: 13
          offer_id: 8
          partner_id: 27
          uid: 114
          offer_status: 23
          total_clubs_mapped: 112
          additional_specifications: 107
          of_authorized_to_sign: 108
          of_partner_rep_name: 101
          of_partner_rep_title: 102
          of_partner_rep_email: 103
          of_decline_offer_reasons: 110
          of_declined_offer_reason_other: 123
          of_approval_status: 109
          of_submit_timestamp: 104
          of_partner_ip: 105
          of_partner_location: 106
      partners:
        db: bksfqeuc2
        fields:
          id: 3
          category_name: 75
          partner_name: 6
          type_of_product: 73
          partner_location_count: 80
          payment_terms: 39
      offers:
        db: bksfqeufh
        fields:
          id: 3
          cost_to_incomm_per_each: 69
          offer_details: 6
          partner_id: 18
          total_offer_cost: 22
          total_margin: 50
          customer_discount_margin: 52
          total_incomm_margin: 51
          balance_inquery_method: 34
      rounds:
        db: bksfqeuhe
        fields:
          id: 3
          sales_period_start: 18
          sales_period_end: 19
      assets:
        db: bksfqeur5
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 23
          balance_enquire_method: 12
          product_image: 21
          product_image2: 76
          product_image3: 88
          product_image4: 89
          partner_logo: 17
          partner_logo2: 78
          gift_card_image: 16
          gift_card_image2: 77
          offer_id: 8

production:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: fz95s79adpvhcv5b26idhqqwk2
    referrences:
      assets:
        db: bj9ghvm9w
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 23
          balance_enquire_method: 12
          product_image: 21
          product_image2: 76
          partner_logo: 17
          partner_logo2: 78
          product_image3: 88
          product_image4: 89
          gift_card_image: 16
          gift_card_image2: 77
          offer_id: 8
      enrollments:
        db: bjjknsqq3
        fields:
          id: 3
          round_id: 13
          offer_id: 8
          partner_id: 27
          uid: 120
          offer_status: 23
          total_clubs_mapped: 112
          additional_specifications: 107
          of_authorized_to_sign: 108
          of_partner_rep_name: 101
          of_partner_rep_title: 102
          of_partner_rep_email: 103
          of_decline_offer_reasons: 110
          of_declined_offer_reason_other: 146
          of_approval_status: 109
          of_submit_timestamp: 104
          of_partner_ip: 105
          of_partner_location: 106
      offers:
        db: bjitjdsxt
        fields:
          id: 3
          cost_to_incomm_per_each: 69
          offer_details: 6
          partner_id: 18
          total_offer_cost: 22
          total_margin: 50
          customer_discount_margin: 52
          total_incomm_margin: 51
          balance_inquery_method: 34
      partners:
        db: bjites2hc
        fields:
          id: 3
          category_name: 75
          partner_name: 6
          type_of_product: 73
          partner_location_count: 80
          payment_terms: 39
      rounds:
        db: bjjhx9fmg
        fields:
          id: 3
          sales_period_start: 18
          sales_period_end: 19

qa:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: bgat66jdufxxh5pafvqybxkfxzt
    referrences:
      assets:
        db: bksfqeur5
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 23
          balance_enquire_method: 12
          product_image: 21
          product_image2: 76
          product_image3: 88
          product_image4: 89
          partner_logo: 17
          partner_logo2: 78
          gift_card_image: 16
          gift_card_image2: 77
          offer_id: 8
      enrollments:
        db: bksfqeuhj
        fields:
          id: 3
          round_id: 13
          offer_id: 8
          partner_id: 27
          uid: 114
          offer_status: 23
          total_clubs_mapped: 112
          additional_specifications: 107
          of_authorized_to_sign: 108
          of_partner_rep_name: 101
          of_partner_rep_title: 102
          of_partner_rep_email: 103
          of_decline_offer_reasons: 110
          of_declined_offer_reason_other: 123
          of_approval_status: 109
          of_submit_timestamp: 104
          of_partner_ip: 105
          of_partner_location: 106
      partners:
        db: bksfqeuc2
        fields:
          id: 3
          category_name: 75
          partner_name: 6
          type_of_product: 73
          partner_location_count: 80
          payment_terms: 39
      offers:
        db: bksfqeufh
        fields:
          id: 3
          offer_details: 6
          partner_id: 18
          total_offer_cost: 22
          total_margin: 50
          customer_discount_margin: 52
          total_incomm_margin: 51
          balance_inquery_method: 34
          cost_to_incomm_per_each: 69
      rounds:
        db: bksfqeuhe
        fields:
          id: 3
          sales_period_start: 18
          sales_period_end: 19
