development:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: fz95s79adpvhcv5b26idhqqwk2
    referrences:
      offer_assets:
        db: bj9ghvm9w
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 14
          balance_enquire_method: 12
          product_image: 21
          partner_logo: 17
          gift_card_image: 16
          oid: 8

production:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: fz95s79adpvhcv5b26idhqqwk2
    referrences:
      offer_assets:
        db: bj9ghvm9w
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 14
          balance_enquire_method: 12
          product_image: 21
          partner_logo: 17
          gift_card_image: 16
          oid: 8

qa:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: fz95s79adpvhcv5b26idhqqwk2
    referrences:
      offer_assets:
        db: bj9ghvm9w
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 14
          balance_enquire_method: 12
          product_image: 21
          partner_logo: 17
          gift_card_image: 16
          oid: 8
