development:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: bgat66jdufxxh5pafvqybxkfxzt
    referrences:
      enrollments:
        url: 'http://evo.incomm.leansquad.com/enrollments/'
        db: bksfqeuhj
        fields:
          cycle_id: 13
          offer_id: 8
          partner_id: 31
          url_id: 113
          offer_status: 23
          enrollment_id: 3
      offer_assets:
        db: bksfqeuj6
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 23
          balance_enquire_method: 12
          product_image: 21
          product_image2: 76
          partner_logo: 17
          partner_logo2: 78
          gift_card_image: 16
          gift_card_image2: 77
          offer_id: 8

production:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: fz95s79adpvhcv5b26idhqqwk2
    referrences:
      offer_assets:
        db: bj9ghvm9w
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 23
          balance_enquire_method: 12
          product_image: 21
          product_image2: 76
          partner_logo: 17
          partner_logo2: 78
          gift_card_image: 16
          gift_card_image2: 77
          offer_id: 8

qa:
  quickbase:
    username: quickbase@leansquad.com
    password: lsqb2015!
    org: incomm-5923
    apptoken: fz95s79adpvhcv5b26idhqqwk2
    referrences:
      offer_assets:
        db: bj9ghvm9w
        fields:
          background_color: 19
          terms: 22
          city_or_state: 14
          physical_address: 18
          company_overview: 15
          product_feature: 20
          card_type: 23
          balance_enquire_method: 12
          product_image: 21
          product_image2: 76
          partner_logo: 17
          partner_logo2: 78
          gift_card_image: 16
          gift_card_image2: 77
          offer_id: 8
