development:
  adapter: postgresql
  database: paa_development
  username: amamrenko
  password: 
  host: localhost

test:
   adapter: postgresql
   database: paa_test
   username: amamrenko
   password: 
   host: localhost
# 
# production:
#   adapter: postgresql
#   database: dekvlg450l1hcb
#   username: dthsfproojphtu
#   password: imvWjYvw9NB47JuYbsFXzU0WQo
#   host: ec2-174-129-21-42.compute-1.amazonaws.com
